In [1]:
import numpy as np

In [2]:
Z=np.zeros((5,5),dtype=np.float64)
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
print(Z.size,Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

25 8
200 bytes


In [4]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
a=np.full((1,10),0)
a=a[0,:]
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
a=np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
lst=[1,2,0,0,4,0]
a=np.array(lst)
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random((3,3,3))

array([[[0.55958322, 0.64328152, 0.36696282],
        [0.83555452, 0.62687819, 0.22241059],
        [0.96243768, 0.55045228, 0.56687516]],

       [[0.8438528 , 0.435978  , 0.92449413],
        [0.46198431, 0.38555666, 0.3738058 ],
        [0.6301351 , 0.14832952, 0.6835486 ]],

       [[0.27646106, 0.91032179, 0.18093575],
        [0.09069487, 0.93761571, 0.21068456],
        [0.98979408, 0.23091557, 0.82690176]]])

In [14]:
np.random.rand(3,3,3)

array([[[0.75972698, 0.71968972, 0.33130352],
        [0.44317549, 0.05194619, 0.41906855],
        [0.12957074, 0.53622711, 0.50467371]],

       [[0.05298334, 0.15530728, 0.5577126 ],
        [0.94842346, 0.38088132, 0.60750392],
        [0.57674917, 0.57757764, 0.56645552]],

       [[0.50316177, 0.60532682, 0.14093422],
        [0.051389  , 0.89121182, 0.851962  ],
        [0.27638378, 0.93234973, 0.25845189]]])

In [15]:
np.random.rand(3)

array([0.24159486, 0.56503786, 0.69443393])

In [16]:
a=np.random.rand(10,10)
a.min()

0.005295128089796708

In [17]:
a.max()

0.993886011673581

In [18]:
np.random.rand(30).mean()

0.5006846878385255

In [19]:
np.set_printoptions(suppress=True,precision=8)

In [20]:
a=np.zeros(25).reshape(5,5)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
a[[0,-1]]=1
a[:,[0,-1]]=1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
a=np.full((5,5),1)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
a=np.pad(a,pad_width=1,mode="constant",constant_values=0)
a

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [25]:
print(np.inf>np.nan)
print(np.inf==np.nan)
print(np.inf<np.nan)
print(np.inf-np.nan)

False
False
False
nan


In [26]:
print(np.nan-np.nan)

nan


In [27]:
set_=set([np.nan,1,0])
print(set_)
print(np.inf in set([np.inf]))

{nan, 1, 0}
True


In [28]:
print(0.3 == 3 * 0.1)
print(3*0.1)

False
0.30000000000000004


In [29]:
a=np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [30]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [31]:
print(np.unravel_index([0,1,2,3,4,5,6,7,8],(3,3)))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


In [32]:
a=np.zeros((1,1))
np.tile(a,(2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
a=np.zeros((2,2))
a[0,1]=1
a[1,0]=1
np.tile(a,(4,4))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [34]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [35]:
a=np.random.random((5,5))
a

array([[0.6408542 , 0.39796495, 0.65399451, 0.67590731, 0.7663206 ],
       [0.05056791, 0.65940234, 0.06833338, 0.97068693, 0.98737912],
       [0.63978998, 0.01685174, 0.63588015, 0.33100645, 0.14481757],
       [0.00079268, 0.59736417, 0.13134688, 0.86630979, 0.63111734],
       [0.16263042, 0.75260236, 0.95405048, 0.76858634, 0.19832165]])

In [36]:
a=(a-np.mean(a))/(np.var(a))
a

array([[ 1.30337574, -1.08157428,  1.43240158,  1.64756522,  2.53534092],
       [-4.49269525,  1.48550151, -4.31825461,  4.54203121,  4.70593321],
       [ 1.29292611, -4.82375717,  1.25453515, -1.73904549, -3.56724984],
       [-4.98144238,  0.87634343, -3.6995197 ,  3.51714324,  1.20776873],
       [-3.39234393,  2.4006404 ,  4.37867655,  2.55758843, -3.04188879]])

In [37]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-37-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [38]:
print(np.zeros((3,3)))
a=np.zeros((3,3),dtype=color)
a

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)],
       [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)],
       [(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)]],
      dtype=[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [39]:
a1=np.arange(15).reshape(5,3)
a2=np.ones((3,2))
print(a1,a2,sep="\n")
print(np.dot(a1,a2))
np.multiply([1,2,3],[2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 3.  3.]
 [12. 12.]
 [21. 21.]
 [30. 30.]
 [39. 39.]]


array([2, 4, 6])

In [40]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
a[(a>3)&(a<=8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [42]:
print(sum(range(6),-1))
print(sum(range(6)))

14
15


In [43]:
print(sum(np.arange(6),-1))
print(np.sum(np.arange(6),-1))
print(sum(range(6),-1))
print(np.sum(range(6),-1))

14
15
14
15


In [45]:
Z=np.arange(10)
np.add.reduce(Z)

45

In [54]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
equal= np.allclose(A,B)
print(equal)

[1 1 0 0 1] [1 1 0 0 1]
True


In [51]:
equal = np.array_equal(A,B)
print(equal)

False


In [59]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0]=1

ValueError: assignment destination is read-only

In [70]:
Z = np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
X,Y

(array([0.9046946 , 0.72451831, 0.8296779 , 0.71451771, 0.48172819,
        0.53368909, 0.65725587, 0.46788628, 0.93237813, 0.55341316]),
 array([0.46756703, 0.63786444, 0.22295797, 0.47797121, 0.43097661,
        0.7870283 , 0.12456167, 0.86611961, 0.11037478, 0.02648475]))

In [72]:
R = np.sqrt(X**2 + Y**2)
R

array([1.01837677, 0.96529676, 0.85911331, 0.85964646, 0.64637674,
       0.95091408, 0.66895508, 0.98441899, 0.93888848, 0.55404653])

In [73]:
T = np.arctan2(Y,X)

[0.4770153  0.72187908 0.26252621 0.58957648 0.72984968 0.97491552
 0.18729649 1.07550066 0.11783147 0.04782062]


In [92]:
Z = np.random.random(10).reshape((2,5))
shape = Z.shape
Z = Z.ravel()
Z[np.argmax(Z)] = 0
Z.reshape(shape)

array([[0.1865868 , 0.31437075, 0.28886755, 0.        , 0.39712623],
       [0.14333765, 0.35776072, 0.30618767, 0.45459856, 0.63989456]])

In [102]:
Z = np.zeros((5,5), [("x", float),("y", float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [106]:
Z["x"],Z["y"]

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [116]:
Z["x"] = np.linspace(0,1,5)
Z["y"] = np.linspace(0,1,5)
Z

array([[(0.  , 0.  ), (0.25, 0.25), (0.5 , 0.5 ), (0.75, 0.75),
        (1.  , 1.  )],
       [(0.  , 0.  ), (0.25, 0.25), (0.5 , 0.5 ), (0.75, 0.75),
        (1.  , 1.  )],
       [(0.  , 0.  ), (0.25, 0.25), (0.5 , 0.5 ), (0.75, 0.75),
        (1.  , 1.  )],
       [(0.  , 0.  ), (0.25, 0.25), (0.5 , 0.5 ), (0.75, 0.75),
        (1.  , 1.  )],
       [(0.  , 0.  ), (0.25, 0.25), (0.5 , 0.5 ), (0.75, 0.75),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [123]:
Z["x"],Z["y"] = np.meshgrid(np.linspace(0,4,5),np.linspace(0,4,5))
Z

array([[(0., 0.), (1., 0.), (2., 0.), (3., 0.), (4., 0.)],
       [(0., 1.), (1., 1.), (2., 1.), (3., 1.), (4., 1.)],
       [(0., 2.), (1., 2.), (2., 2.), (3., 2.), (4., 2.)],
       [(0., 3.), (1., 3.), (2., 3.), (3., 3.), (4., 3.)],
       [(0., 4.), (1., 4.), (2., 4.), (3., 4.), (4., 4.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [120]:
m, n = 5, 4
x = np.linspace(0, m-1, m)
y = np.linspace(0, n-1, n)
X, Y = np.meshgrid(x, y)
print(x,y)
print(X,Y)

[0. 1. 2. 3. 4.] [0. 1. 2. 3.]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]] [[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]]


In [128]:
Z = np.random.rand(5,5)
z = 0.5
Z

array([[0.41598074, 0.82256711, 0.14509073, 0.48400674, 0.94497558],
       [0.70476213, 0.90329432, 0.23514784, 0.71532397, 0.09213157],
       [0.64738904, 0.97746965, 0.43000403, 0.542275  , 0.10080336],
       [0.08705871, 0.05849666, 0.03032359, 0.31288882, 0.71357018],
       [0.22821562, 0.43932021, 0.00050548, 0.49309923, 0.85158784]])

In [129]:
Z[np.unravel_index(np.argmin(np.abs(Z-z)),Z.shape)]

0.49309922825143115