In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)

In [3]:
a>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [5]:
a[(a>12)|(a<3)]=0
a

array([[ 0,  0,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  0,  0,  0]])

In [7]:
a[1]=1
a

array([[ 0,  0,  0,  3],
       [ 1,  1,  1,  1],
       [ 8,  9, 10, 11],
       [12,  0,  0,  0]])

In [9]:
np.where(a < 10 ,1 , 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1]])

In [10]:
a1=np.random.random((3,4))
a1

array([[0.40550078, 0.30902418, 0.00175021, 0.97456681],
       [0.55330932, 0.5839067 , 0.09486   , 0.63901747],
       [0.67338367, 0.68771238, 0.22346851, 0.26711456]])

In [11]:
a1*10

array([[4.05500775, 3.09024185, 0.01750208, 9.74566811],
       [5.53309318, 5.83906702, 0.94859999, 6.39017472],
       [6.73383673, 6.87712377, 2.23468515, 2.67114562]])

In [13]:
a=a1.round()
a

array([[0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [17]:
a

array([[0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [18]:
a.size

12

In [19]:
a.itemsize

8

In [20]:
a.shape

(3, 4)

In [24]:
a1=a.reshape((12,))
a1

array([0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.])

In [25]:
a

array([[0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [26]:
a.flatten()

array([0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.])

In [27]:
a

array([[0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [30]:
b=a.ravel()
b

array([0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.])

In [29]:
a

array([[0., 0., 0., 1.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [31]:
b[0:4]=1000

In [32]:
a

array([[1000., 1000., 1000., 1000.],
       [   1.,    1.,    0.,    1.],
       [   1.,    1.,    0.,    0.]])

In [34]:
a1 = np.arange(16.0).reshape(4, 4)
a1

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [35]:
np.split(a1,2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [38]:
np.hsplit(a1,[0,2])

[array([], shape=(4, 0), dtype=float64),
 array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [39]:
np.array_split(a1,[0,2],axis=0)

[array([], shape=(0, 4), dtype=float64),
 array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [40]:
np.array_split(a1,[0,2],axis=1)

[array([], shape=(4, 0), dtype=float64),
 array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [41]:
a1 = np.arange(0,24).reshape((4,6))

In [44]:
a2=a1.transpose()
a2

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [45]:
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [47]:
a2[2]=1
a2

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 1,  1,  1,  1],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [48]:
a1

array([[ 0,  1,  1,  3,  4,  5],
       [ 6,  7,  1,  9, 10, 11],
       [12, 13,  1, 15, 16, 17],
       [18, 19,  1, 21, 22, 23]])

In [51]:
a1[:,[1,2,3]]

array([[ 1,  1,  3],
       [ 7,  1,  9],
       [13,  1, 15],
       [19,  1, 21]])

In [52]:
a1[0:2,2:3]

array([[1],
       [1]])

In [53]:
a1[1,1]

7

In [55]:
a1[[0,1,2,3],[0,1,2,3]]=1
a1

array([[ 1,  1,  1,  3,  4,  5],
       [ 6,  1,  1,  9, 10, 11],
       [12, 13,  1, 15, 16, 17],
       [18, 19,  1,  1, 22, 23]])

In [56]:
scores = np.random.randint(0,100,size=(20,2))
scores

array([[78,  0],
       [59,  5],
       [56, 68],
       [55, 67],
       [78, 25],
       [18,  1],
       [ 8, 35],
       [80, 37],
       [79,  6],
       [35, 81],
       [23, 99],
       [18, 23],
       [ 0, 28],
       [72, 14],
       [ 5, 47],
       [29, 93],
       [28, 65],
       [26, 62],
       [88, 37],
       [76, 43]])

In [65]:
np.savetxt("scores.csv",scores,fmt="%d",header="数学,语文",comments="",delimiter=",")

In [70]:
np.loadtxt("scores.csv",skiprows=1,delimiter=",",dtype="i1",usecols=(1,),unpack=True)

array([ 0,  5, 68, 67, 25,  1, 35, 37,  6, 81, 99, 23, 28, 14, 47, 93, 65,
       62, 37, 43], dtype=int8)

In [71]:
import csv

In [78]:
with open('scores.csv','r') as f:
    reader = csv.reader(f)
    next(reader)
    for x in reader:
        print(x)

['78', '0']
['59', '5']
['56', '68']
['55', '67']
['78', '25']
['18', '1']
['8', '35']
['80', '37']
['79', '6']
['35', '81']
['23', '99']
['18', '23']
['0', '28']
['72', '14']
['5', '47']
['29', '93']
['28', '65']
['26', '62']
['88', '37']
['76', '43']


In [79]:
with open('scores.csv','r') as f:
    reader = csv.DictReader(f)
    for x in reader:
        print(x)

{'数学': '78', '语文': '0'}
{'数学': '59', '语文': '5'}
{'数学': '56', '语文': '68'}
{'数学': '55', '语文': '67'}
{'数学': '78', '语文': '25'}
{'数学': '18', '语文': '1'}
{'数学': '8', '语文': '35'}
{'数学': '80', '语文': '37'}
{'数学': '79', '语文': '6'}
{'数学': '35', '语文': '81'}
{'数学': '23', '语文': '99'}
{'数学': '18', '语文': '23'}
{'数学': '0', '语文': '28'}
{'数学': '72', '语文': '14'}
{'数学': '5', '语文': '47'}
{'数学': '29', '语文': '93'}
{'数学': '28', '语文': '65'}
{'数学': '26', '语文': '62'}
{'数学': '88', '语文': '37'}
{'数学': '76', '语文': '43'}


In [80]:
headers = ['name','age','classroom']
values = [
    ('zhiliao',18,'111'),
    ('wena',20,'222'),
    ('bbc',21,'111')
]

In [83]:
with open("text.csv","w",newline="") as f:
    writer=csv.writer(f)
    writer.writerow(headers)
    writer.writerows(values)

In [84]:
with open('text.csv','r') as f:
    reader = csv.reader(f)
    for x in reader:
        print(x)

['name', 'age', 'classroom']
['zhiliao', '18', '111']
['wena', '20', '222']
['bbc', '21', '111']
