In [1]:
import numpy as np

In [10]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a.reshape(12,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
a.size

12

In [15]:
a.shape

(12,)

In [18]:
a.ndim

1

In [19]:
a.itemsize

4

In [20]:
a.dtype

dtype('int32')

In [21]:
a.astype("i1")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int8)

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
a.itemsize

4

In [27]:
a1=np.random.randint(1,10,(3,4))
a2=np.full((4,2),2)
a1

array([[6, 5, 2, 8],
       [1, 5, 1, 9],
       [5, 6, 2, 3]])

In [25]:
np.dot(a1,a2)

array([[38, 38],
       [52, 52],
       [52, 52]])

In [31]:
a1=np.random.random((2,3))
a1

array([[0.32822079, 0.31225373, 0.28010748],
       [0.26448599, 0.98450815, 0.19288129]])

In [32]:
a1.round(2)

array([[0.33, 0.31, 0.28],
       [0.26, 0.98, 0.19]])

In [33]:
a1

array([[0.32822079, 0.31225373, 0.28010748],
       [0.26448599, 0.98450815, 0.19288129]])

In [35]:
np.(a1)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
a1=np.full((4,4),1)

In [37]:
a2=np.full((4,1),2)

In [38]:
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [39]:
a2

array([[2],
       [2],
       [2],
       [2]])

In [40]:
a1-a2

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [55]:
a1=np.full((2,1,3),2)
a2=np.full((2,3,1),1)
print(a1)
print(a2)

[[[2 2 2]]

 [[2 2 2]]]
[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]]


In [56]:
a1-a2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [46]:
a1=np.full((1,3),2)
a2=np.full((3,1),1)
print(a1)
print(a2)

[[2 2 2]]
[[1]
 [1]
 [1]]


In [47]:
a1-a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
a1=np.full((3,3),3)
a2=np.full((3,1),2)
print(a1)
print(a2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[2]
 [2]
 [2]]


In [51]:
a1-a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
a1

array([[[2, 2, 2]],

       [[2, 2, 2]]])

In [58]:
a2

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [59]:
a1.resize(6,)

In [60]:
a1

array([2, 2, 2, 2, 2, 2])

In [61]:
a1 = np.random.randint(0,10,size=(3,2))
a2 = np.random.randint(0,10,size=(3,1))

In [63]:
np.hstack([a1,a2])

array([[0, 8, 1],
       [4, 5, 8],
       [2, 6, 4]])