In [1]:
import numpy as np

In [2]:
data = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding="utf-8",dtype=np.str)

<ipython-input-2-f5813032ff46>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding="utf-8",dtype=np.str)


In [3]:
data

array([['59', '89'],
       ['90', '32'],
       ['78', '45.5'],
       ['34', ''],
       ['', '56'],
       ['23', '56']], dtype='<U4')

In [4]:
data[data=='']=0
data

array([['59', '89'],
       ['90', '32'],
       ['78', '45.5'],
       ['34', '0'],
       ['0', '56'],
       ['23', '56']], dtype='<U4')

In [5]:
data=data.astype(np.float)
data

<ipython-input-5-31b1b141de29>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data=data.astype(np.float)


array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  0. ],
       [ 0. , 56. ],
       [23. , 56. ]])

In [6]:
data[data==0]=np.nan
data

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  nan],
       [ nan, 56. ],
       [23. , 56. ]])

In [7]:
nan_line = np.where(np.isnan(data))[0]
nan_line

array([3, 4], dtype=int64)

In [8]:
np.delete(data,nan_line,axis=0)

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [23. , 56. ]])

In [9]:
data1=data.copy()
data1

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  nan],
       [ nan, 56. ],
       [23. , 56. ]])

In [10]:
for i in range(data.shape[1]):
    col = data[:,i]
    mean = col[~np.isnan(col)].mean()
    col[np.isnan(col)]=mean
    print(col)

[59.  90.  78.  34.  56.8 23. ]
[89.  32.  45.5 55.7 56.  56. ]


In [11]:
data1

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  nan],
       [ nan, 56. ],
       [23. , 56. ]])