In [2]:
import numpy as np

In [9]:
data = np.random.randint(1,10,size=(3,5)).astype(np.float64)
data

array([[4., 7., 7., 3., 4.],
       [3., 3., 8., 5., 8.],
       [7., 4., 7., 6., 1.]])

In [10]:
data[0,1]=np.nan
data[2,3]=np.nan
data

array([[ 4., nan,  7.,  3.,  4.],
       [ 3.,  3.,  8.,  5.,  8.],
       [ 7.,  4.,  7., nan,  1.]])

In [11]:
np.isnan(data)

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [15]:
data[np.isnan(data)]


array([4., 7., 3., 4., 3., 3., 8., 5., 8., 7., 4., 7., 1.])

In [16]:
data[~np.isnan(data)]

array([4., 7., 3., 4., 3., 3., 8., 5., 8., 7., 4., 7., 1.])

In [17]:
np.where(np.isnan(data))

(array([0, 2], dtype=int64), array([1, 3], dtype=int64))

In [18]:
np.where(np.isnan(data))[0]

array([0, 2], dtype=int64)

In [19]:
np.delete(data,1,axis=0)

array([[ 4., nan,  7.,  3.,  4.],
       [ 7.,  4.,  7., nan,  1.]])

In [24]:
np.delete(data,np.where(np.isnan(data))[0],axis=0)

array([[3., 3., 8., 5., 8.]])

In [33]:
scores = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding="utf-8",dtype=str)
scores

array([['59', '89'],
       ['90', '32'],
       ['78', '45.5'],
       ['34', ''],
       ['', '56'],
       ['23', '56']], dtype='<U4')

In [37]:
scores[scores==""]=np.nan
scores

array([['59', '89'],
       ['90', '32'],
       ['78', '45.5'],
       ['34', 'nan'],
       ['nan', '56'],
       ['23', '56']], dtype='<U4')

In [55]:
scores1=scores.astype(np.float64)
scores1

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  0. ],
       [ 0. , 56. ],
       [23. , 56. ]])

In [56]:
scores1[np.isnan(scores1)]=0
scores1

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  0. ],
       [ 0. , 56. ],
       [23. , 56. ]])

In [57]:
scores1.sum(axis=1).astype(np.int8)

array([-108,  122,  123,   34,   56,   79], dtype=int8)

In [59]:
scores1.shape

(6, 2)

In [63]:
scores1[scores1==0]=np.nan
scores1

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. ,  nan],
       [ nan, 56. ],
       [23. , 56. ]])

In [69]:
for col_index in range(scores1.shape[1]):
    col=scores1[:,col_index]
    non_nan_col=col[~np.isnan(col)]
    mean_=non_nan_col.mean()
    col[np.isnan(col)]=mean_
scores1
    

array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. , 55.7],
       [56.8, 56. ],
       [23. , 56. ]])