In [2]:
import numpy as np
print(np.__version__)

1.20.1


In [3]:
np.full((4,4),False)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [10]:
arr = np.arange(10)
arr.reshape(2,5) #转换成(2,5)的数组
arr[:,np.newaxis] #转换成(10,1)的数组

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
arr = np.random.randint(0,10,size=(10,2))
arr1 = arr[:,np.newaxis,:]
print(arr1.shape)

(10, 1, 2)


In [12]:
arr1

array([[[5, 8]],

       [[2, 5]],

       [[4, 4]],

       [[2, 9]],

       [[7, 1]],

       [[5, 3]],

       [[7, 2]],

       [[5, 3]],

       [[7, 5]],

       [[8, 6]]])

In [24]:
arr = np.arange(10)
arr=arr.reshape(2,5) #转换成(2,5)的数组
arr[:,1]

array([1, 6])

In [3]:
arr=np.random.randint(1,10,size=(5,5))
arr

array([[1, 3, 1, 2, 8],
       [4, 6, 9, 6, 7],
       [1, 9, 2, 4, 7],
       [1, 6, 5, 9, 6],
       [6, 6, 8, 5, 8]])

In [4]:
arr_new= np.where(arr%2==0,0,arr)

In [5]:
arr_new

array([[1, 3, 1, 0, 0],
       [0, 0, 9, 0, 7],
       [1, 9, 0, 0, 7],
       [1, 0, 5, 9, 0],
       [0, 0, 0, 5, 0]])

In [13]:
arr

array([[1, 3, 1, 2, 8],
       [4, 6, 9, 6, 7],
       [1, 9, 2, 4, 7],
       [1, 6, 5, 9, 6],
       [6, 6, 8, 5, 8]])

In [16]:
arr[np.logical_or(arr%2==0,arr==1)]=0
arr

array([[0, 3, 0, 0, 0],
       [0, 0, 9, 0, 7],
       [0, 9, 0, 0, 7],
       [0, 0, 5, 9, 0],
       [0, 0, 0, 5, 0]])

In [19]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [22]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
index=np.where(np.logical_and(a>=5,a<=10))
index

(array([1, 1, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 3, 4, 0], dtype=int64))

In [26]:
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
a[(a>=5) & (a<=10)]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [33]:
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10]])

In [50]:
np.set_printoptions(suppress=True,precision=10)

In [51]:
arr=np.random.random((3,3))/1e3
arr

array([[0.0002940312, 0.0003131015, 0.0008460638],
       [0.0005852913, 0.0007705137, 0.0003171869],
       [0.0000615768, 0.0003486134, 0.0007806365]])

In [52]:
arr = np.random.randint(0,20,(10,10))

In [53]:
np.unique(arr,return_counts=True)

(array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([2, 4, 9, 2, 7, 1, 9, 5, 8, 5, 3, 5, 6, 4, 7, 6, 5, 5, 7],
       dtype=int64))