In [2]:
import numpy as np

In [7]:
a=np.random.rand(10,2)
a

array([[0.37230044, 0.82654436],
       [0.9845884 , 0.43039359],
       [0.60138606, 0.20019108],
       [0.21221411, 0.24030531],
       [0.90664915, 0.39661843],
       [0.29496655, 0.60941688],
       [0.86911373, 0.16326724],
       [0.39125839, 0.09775122],
       [0.06820659, 0.2327319 ],
       [0.4129462 , 0.06174095]])

In [12]:
np.savetxt("array.csv",a,fmt="%.2f",delimiter=",",header="语文,数学",comments="")

In [19]:
np.loadtxt("array.csv",delimiter=",",skiprows=1)

array([[0.37, 0.83],
       [0.98, 0.43],
       [0.6 , 0.2 ],
       [0.21, 0.24],
       [0.91, 0.4 ],
       [0.29, 0.61],
       [0.87, 0.16],
       [0.39, 0.1 ],
       [0.07, 0.23],
       [0.41, 0.06]])

In [20]:
a1=np.random.randint(0,10,size=(3,3,3))
np.save("a1",a1)

In [23]:
np.load("a1.npy")

array([[[0, 5, 9],
        [2, 7, 0],
        [4, 2, 3]],

       [[6, 2, 1],
        [1, 7, 9],
        [8, 9, 3]],

       [[4, 5, 4],
        [5, 7, 4],
        [6, 8, 1]]])