In [1]:
import numpy as np

In [2]:
a=np.random.uniform(-10,10,size=(3,5))
a

array([[-5.0362082 ,  1.66962383, -0.81887208,  8.04031006, -6.73005131],
       [-7.68033391, -9.33148217,  0.71656273, -6.94167723, -8.91283303],
       [-5.64895992, -9.88919043,  8.02140442,  4.16299153, -6.65425059]])

In [3]:
np.sort(a)

array([[-6.73005131, -5.0362082 , -0.81887208,  1.66962383,  8.04031006],
       [-9.33148217, -8.91283303, -7.68033391, -6.94167723,  0.71656273],
       [-9.88919043, -6.65425059, -5.64895992,  4.16299153,  8.02140442]])

In [4]:
np.sort(a,axis=0)

array([[-7.68033391, -9.88919043, -0.81887208, -6.94167723, -8.91283303],
       [-5.64895992, -9.33148217,  0.71656273,  4.16299153, -6.73005131],
       [-5.0362082 ,  1.66962383,  8.02140442,  8.04031006, -6.65425059]])

In [5]:
np.argsort(a)

array([[4, 0, 2, 1, 3],
       [1, 4, 0, 3, 2],
       [1, 4, 0, 3, 2]])

In [6]:
np.argsort(a,axis=0)

array([[1, 2, 0, 1, 1],
       [2, 1, 1, 2, 0],
       [0, 0, 2, 0, 2]])

In [7]:
-np.sort(-a)

array([[ 8.04031006,  1.66962383, -0.81887208, -5.0362082 , -6.73005131],
       [ 0.71656273, -6.94167723, -7.68033391, -8.91283303, -9.33148217],
       [ 8.02140442,  4.16299153, -5.64895992, -6.65425059, -9.88919043]])

In [8]:
np.argsort(-a)

array([[3, 1, 2, 0, 4],
       [2, 3, 0, 4, 1],
       [2, 3, 0, 4, 1]])

In [9]:
np.take(a,0)

-5.036208203433432

In [13]:
a1=np.random.uniform(-10,10,size=(3,5))
a1

array([[ 6.7194926 , -3.22198285,  2.83577765,  2.05879467, -0.39209602],
       [-0.89602377, -4.06306143, -1.17149821,  7.34912757, -7.5988248 ],
       [ 7.24251815,  3.50985717,  1.31105424,  6.76792874, -6.16617546]])

In [15]:
np.abs(a)

array([[5.0362082 , 1.66962383, 0.81887208, 8.04031006, 6.73005131],
       [7.68033391, 9.33148217, 0.71656273, 6.94167723, 8.91283303],
       [5.64895992, 9.88919043, 8.02140442, 4.16299153, 6.65425059]])

In [17]:
a1=np.full((2,3),4)
a1

array([[4, 4, 4],
       [4, 4, 4]])

In [18]:
np.sqrt(a1)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [20]:
np.square(a1)

array([[16, 16, 16],
       [16, 16, 16]])

In [22]:
a2=np.exp(a1)

In [24]:
np.log(a2)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [25]:
a3=np.full((3,3),100)

In [26]:
np.log10(a3)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [30]:
a4=np.random.uniform(-2,2,size=(3,3))
a4

array([[-1.06150893, -1.47668143,  0.41295961],
       [ 1.77937864,  0.98040595,  0.4543713 ],
       [-1.25471284, -0.41665842, -1.93558661]])

In [35]:
np.sign(a4).astype(np.int8)

array([[-1, -1,  1],
       [ 1,  1,  1],
       [-1, -1, -1]], dtype=int8)

In [38]:
a5=[3.2]
np.ceil(a5)

array([4.])

In [39]:
np.floor(a5)

array([3.])

In [44]:
%time np.sum(np.arange(100000000))

CPU times: user 295 ms, sys: 302 ms, total: 596 ms
Wall time: 626 ms


4999999950000000

In [45]:
%time sum(range(100000000))

CPU times: user 1.89 s, sys: 16.8 ms, total: 1.91 s
Wall time: 1.92 s


4999999950000000

In [48]:
a5=np.arange(100).reshape(10,10)
a5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
a5%10==0

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False]])

In [61]:
a5=a5.astype(np.float64)
a5

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [ 0., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [ 0., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [ 0., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [ 0., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [ 0., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [ 0., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [ 0., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [ 0., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [62]:
a5[a5%10==0]=np.nan

In [67]:
~np.isnan(a5)

array([[False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [100]:
a6=np.random.randn(3,3)*10
a6

array([[ 15.13768949,   5.94428731,   6.31133427],
       [-12.11062177,  -5.05873669,  -6.25406247],
       [ -9.6829517 ,   9.09368654,  -6.04163159]])

In [101]:
np.modf(a6)

(array([[ 0.13768949,  0.94428731,  0.31133427],
        [-0.11062177, -0.05873669, -0.25406247],
        [-0.6829517 ,  0.09368654, -0.04163159]]),
 array([[ 15.,   5.,   6.],
        [-12.,  -5.,  -6.],
        [ -9.,   9.,  -6.]]))

In [102]:
np.modf(a6)[0]

array([[ 0.13768949,  0.94428731,  0.31133427],
       [-0.11062177, -0.05873669, -0.25406247],
       [-0.6829517 ,  0.09368654, -0.04163159]])

In [103]:
np.modf(a6)[1]

array([[ 15.,   5.,   6.],
       [-12.,  -5.,  -6.],
       [ -9.,   9.,  -6.]])

In [104]:
a6=np.random.randn(3,3)
a6[1,1]=np.inf
a6

array([[ 0.55236138, -0.56682641, -0.2474425 ],
       [ 1.35507726,         inf, -0.59796962],
       [ 2.43257649,  1.6125081 , -0.07765342]])

In [105]:
np.isinf(a6)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [106]:
a6[np.isinf(a6)]

array([inf])

In [107]:
a6=a6*np.isinf(a6)
a6

array([[ 0., -0., -0.],
       [ 0., inf, -0.],
       [ 0.,  0., -0.]])

In [109]:
np.sin(np.array([[3.14/2,3.14/3],[3.14/6,3.14]]))

array([[0.99999968, 0.86575984],
       [0.4997701 , 0.00159265]])

In [116]:
np.arcsin([0.5])

array([0.52359878])

In [117]:
np.divide([4,6,8],[2])

array([2., 3., 4.])

In [118]:
np.floor_divide([2,3,5],3)

array([0, 1, 1])

In [129]:
a1=[[1,2,3],[2,3,67]]
a2=[[0,3,1],[3,2,5]]

In [141]:
np.greater_equal(a1,a2)

array([[ True, False,  True],
       [False,  True,  True]])

In [151]:
a1=np.array([[1,2,3],[2,3,67]])
a1

array([[ 1,  2,  3],
       [ 2,  3, 67]])

In [152]:
a1[(a1>60)|(a1<3)]

array([ 1,  2,  2, 67])

In [157]:
a1[np.logical_or(a1>6,a1<3)]

array([ 1,  2,  2, 67])

In [158]:
np.median(a1)

2.5

In [159]:
np.argmax(a1)

5

In [160]:
np.any(a1>3)

True

In [162]:
np.all(a1>0)

True

In [163]:
np.all(a1>2)

False

In [166]:
a1=np.random.randint(1,10,size=(3,5))
a1

array([[9, 6, 2, 3, 8],
       [6, 6, 8, 6, 2],
       [4, 7, 8, 2, 7]])

In [167]:
np.sum(a1)

84

In [168]:
np.sum(a1,axis=0)

array([19, 19, 18, 11, 17])

In [169]:
np.sum(a1,axis=1)

array([28, 28, 28])

In [171]:
np.prod(a1,axis=0)

array([216, 252, 128,  36, 112])

In [175]:
a=np.random.random((3,3))
a

array([[0.08364194, 0.25757921, 0.96177997],
       [0.38178226, 0.13224402, 0.77418597],
       [0.21786591, 0.4818244 , 0.00738992]])

In [177]:
(a>0).any()

True

In [178]:
np.any(a>0)

True

In [179]:
np.max(a)

0.961779969940615

In [180]:
a.max()

0.961779969940615

In [182]:
a.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [200]:
a=np.linspace(0,9,9,dtype=np.int8).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 9]], dtype=int8)

In [191]:
np.apply_along_axis(lambda x:x[np.logical_and(x!=x.max(),x!=x.min())].mean(), axis=1,arr=a)

array([1., 4., 7.])

In [192]:
def fun_(x):
    print(x)
    print("="*30)
np.apply_along_axis(fun_, axis=1,arr=a)

[0 1 2]
[3 4 5]
[6 7 9]


array([None, None, None], dtype=object)

In [197]:
a=np.linspace(1,3,4,dtype=np.int8)
a

array([1, 1, 2, 3], dtype=int8)

In [209]:
a=np.random.randint(0,10,size=(5,5))
a

array([[3, 6, 4, 4, 3],
       [9, 4, 3, 5, 2],
       [6, 1, 4, 5, 4],
       [9, 2, 2, 4, 8],
       [8, 2, 8, 2, 6]])

In [210]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [215]:
b=np.unique(a,return_counts=True)
b

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([1, 5, 3, 6, 2, 3, 3, 2]))

In [230]:
for i in b[0]:
    print({b[0][i-1]:b[1][i-1]})

{1: 1}
{2: 5}
{3: 3}
{4: 6}
{5: 2}
{6: 3}
{9: 2}


IndexError: index 8 is out of bounds for axis 0 with size 8