In [1]:
# 数据量较小用LineRegression，较大用SGDRegressor
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.linear_model import Ridge
# 对数据进行标准化
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# 方差和平均误差用来表征测试结果和真实结果的偏差
from sklearn.metrics import mean_squared_error,mean_absolute_error

# 视频教学

In [2]:
# 波士顿房价
boston_house_prise = load_boston()
dir(boston_house_prise)

['DESCR', 'data', 'feature_names', 'filename', 'target']

In [3]:
boston_house_prise.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
boston_house_prise.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [5]:
boston_house_prise.filename

'C:\\software\\Anaconda\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv'

In [6]:
boston_house_prise.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [7]:
# 标准化
Std = StandardScaler()
features = Std.fit_transform(boston_house_prise.data)

In [8]:
# 切分数据
x_train,x_test,y_train,y_test = train_test_split(features, boston_house_prise.target, test_size=0.25)

In [9]:
# LinearRegression训练
lr = LinearRegression()
lr.fit(x_train,y_train)
test_predict = lr.predict(x_test)
# 查看数据误差
print("方差",mean_squared_error(y_test,test_predict))
print("平均误差",mean_absolute_error(y_test,test_predict))
print(test_predict)

方差 24.89170178903683
平均误差 3.459116808919514
[21.73007264 15.35347712 25.27338616 29.30305126 18.80863169 14.445525
 37.4395967  24.98222621 17.76274349 23.3801525  24.1897083  17.31680238
 31.11050816 17.05321408 32.36634982 22.48711429 32.43218175 17.97727572
 33.66464484 30.43105894 30.98805844 39.90450255 36.89299662 37.7594718
 27.7291418  34.91787386 13.86258736 15.17481203 29.03179139 26.4371856
 24.00674532 28.38682963 12.75721648 11.62651528 23.40993337 14.90346055
 34.01110873 34.11038106 25.05853851 29.26779487 28.2869779  28.46455352
 27.00445273 15.53362449 17.14441601 26.75973736 27.4491343  27.83111946
 22.35007661 22.16811084 21.43848738 33.49016934 22.76125806 20.62892036
  6.20432003 21.76787353 34.88678364 26.73125943 17.08367799 24.70609002
 30.66002391 11.51778317 18.96508834  8.36726061 16.22088719 20.83712978
 22.32265916 26.89162363 29.35010351 22.84858959 22.69390321 17.73750718
 35.50563582 17.35772724 23.61834258 12.72409107  8.11077792  8.80093797
 25.2561178

In [10]:
# SGDRegressor训练
sgd = SGDRegressor()
sgd.fit(x_train,y_train)
test_predict = sgd.predict(x_test)
print("方差",mean_squared_error(y_test, test_predict))
print("平均误差",mean_absolute_error(y_test, test_predict))

方差 24.690891553511555
平均误差 3.3924993343564407


In [11]:
# 岭回归
ridge = Ridge(alpha=20)
ridge.fit(x_train, y_train)
test_predict = ridge.predict(x_test)
print("方差",mean_squared_error(y_test, test_predict))
print("平均误差",mean_absolute_error(y_test, test_predict))
# 每个特征值的sita值以及偏移量
print(ridge.coef_)
print(ridge.intercept_)

#对比
# 岭回归
ridge = Ridge(alpha=100000)
ridge.fit(x_train, y_train)
# 每个特征值的sita值以及偏移量
print(ridge.coef_)
print(ridge.intercept_)

方差 24.44268638787371
平均误差 3.3228685292545626
[-0.89620759  0.8369174  -0.47955859  0.80401623 -1.36445359  2.82345638
 -0.32832962 -2.92678015  1.73936322 -1.43934939 -1.8309996   0.62130061
 -3.260403  ]
22.57212337171261
[-0.01450413  0.01278299 -0.01740259  0.00528348 -0.01404667  0.02407954
 -0.0127212   0.00807312 -0.01362592 -0.0167739  -0.01921732  0.01145505
 -0.02478292]
22.342363392022342


# 实例

In [12]:
data = pd.read_excel("data/pv_ppv_pressure.xls",header=None)
data.head(2)

0        1         2         3         4         5        6   \
0  pressure    2.628    2.6381    2.6382    2.6383    2.6384    2.832   
1     2.566  132.176  122.4610  126.5820  122.5210  126.4980  136.069   

         7        8        9        10        11       12       13       14  \
0    2.8321    2.833    2.852    3.679    3.6791    5.233    5.234    5.338   
1  136.1530  141.594  121.314  110.162  110.2780  180.890  180.607  185.526   

         15       16       17  
0    5.3381    6.526    6.723  
1  185.3070  247.908  252.148

In [13]:
# 数据处理
data_new = pd.DataFrame()
columns={"pv":np.nan,"ppv":np.nan,"pressure":np.nan}
data_new.append(columns,ignore_index=True)
for index in list(data.index)[1:]:
    for column in list(data.columns)[1:]:
        pv = data.loc[index,data.columns[0]]
        ppv = data.loc[data.index[0],column]
        pressure = data.loc[index,column]
        every_line_data = pd.DataFrame({"pv":[pv],"ppv":[ppv],"pressure":[pressure]})
        data_new = pd.concat([data_new,every_line_data])
data_new = data_new.reset_index()
data_new.drop("index",axis="columns",inplace=True)
data_new.head()

pv     ppv  pressure
0  2.566  2.6280   132.176
1  2.566  2.6381   122.461
2  2.566  2.6382   126.582
3  2.566  2.6383   122.521
4  2.566  2.6384   126.498

In [14]:
# 分类
features = data_new.drop("pressure",axis=1)
target_pre = data_new["pressure"]
# 将target转为一维数组
target = np.array(target_pre)
features,target

(        pv     ppv
 0    2.566  2.6280
 1    2.566  2.6381
 2    2.566  2.6382
 3    2.566  2.6383
 4    2.566  2.6384
 ..     ...     ...
 335  5.406  5.2340
 336  5.406  5.3380
 337  5.406  5.3381
 338  5.406  6.5260
 339  5.406  6.7230
 
 [340 rows x 2 columns],
 array([132.176, 122.461, 126.582, 122.521, 126.498, 136.069, 136.153,
        141.594, 121.314, 110.162, 110.278, 180.89 , 180.607, 185.526,
        185.307, 247.908, 252.148, 132.054, 122.582, 126.606, 122.64 ,
        126.525, 135.844, 135.922, 141.272, 121.467, 110.478, 110.594,
        181.44 , 181.152, 186.119, 185.903, 248.123, 252.54 , 133.853,
        123.707, 128.064, 123.767, 128.   , 137.879, 137.992, 143.688,
        122.562, 110.987, 111.115, 184.704, 184.397, 189.448, 189.258,
        254.241, 258.631, 133.628, 123.563, 127.879, 123.624, 127.813,
        137.625, 137.734, 143.454, 122.422, 111.057, 111.183, 184.855,
        184.545, 189.642, 189.452, 253.676, 258.073, 125.939, 116.857,
        120.365, 116.89

In [15]:
# 标准化
std = StandardScaler()
features = std.fit_transform(features)

In [16]:
# 切分
x_train,x_test,y_train,y_test = train_test_split(features, target, train_size=0.60)

In [17]:
# LinearRegression训练
lr = LinearRegression()
lr.fit(x_train,y_train)
test_predict = lr.predict(x_test)

In [18]:
# 计算test误差
mean_absolute_error(y_test,test_predict),mean_squared_error(y_test,test_predict)

(13.906745773971338, 328.53767484491823)

In [19]:
# SGDRegressor训练
SGD = SGDRegressor()
SGD.fit(x_train,y_train)
test_predict = SGD.predict(x_test)
# 计算test误差
mean_absolute_error(y_test,test_predict),mean_squared_error(y_test,test_predict)

(13.898778579414966, 328.4797332565907)

In [27]:
from sklearn.metrics import r2_score,mean_absolute_error
# Ridge训练
ridge = Ridge()
ridge.fit(x_train,y_train)
test_predict = ridge.predict(x_test)
# 计算test误差
print("r2",r2_score(y_test,test_predict))
mean_absolute_error(y_test,test_predict),mean_squared_error(y_test,test_predict)

r2 0.810043529123269


(13.867677436935113, 328.18012759660076)

In [21]:
data = [[2.5,2.5],[2.5,3],[2.5,3.5],[2.5,4],[2.5,4.5],[2.5,5]]

In [22]:
data = std.fit_transform(data)

In [23]:
lr.predict(data)

array([ 88.96369936, 109.53871078, 130.11372219, 150.6887336 ,
       171.26374502, 191.83875643])