In [3]:
from sklearn.impute import SimpleImputer
import numpy as np

In [5]:
data=[
    [1,2],
    [np.NAN,4],
    [9,1]
]
si = SimpleImputer()
# 默认是平均值strategy = mean
si.fit_transform(data)

array([[1., 2.],
       [5., 4.],
       [9., 1.]])

In [10]:
# 指定缺失值时nan：missing_values=nan
# 替换缺失值的策略：strategy = [mean,median,most_frequent,constant[fill_value]]
data=[
    [1,2],
    ["?",4],
    [9,1]
]
si1 = SimpleImputer(missing_values="?",strategy="constant",fill_value=20)
si1.fit_transform(data)

array([[1, 2],
       [20, 4],
       [9, 1]], dtype=object)

In [11]:
data=[
    [1,2],
    ["?",4],
    [9,1],
    [9,2]
]
si1 = SimpleImputer(missing_values="?",strategy="most_frequent")
si1.fit_transform(data)

array([[1, 2],
       [9, 4],
       [9, 1],
       [9, 2]], dtype=object)